version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DB_URL=$DB_URL
      - PORT=$PORT
    restart: always
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    container_name: mongoDB
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
